### ISSUE TITLE
Put dungeon prizes in a sane order

### ISSUE THREAD

**Issue by kookookchoozeus** [crossproduct42/alttprandohelper#11]
Regular crystals are most common, then 5/6 crystals tied with regular pendants, then the green pendant is least common, so that's the order they should show up in when you click on a dungeon's prize

I tried to push a branch to your repo, but didn't have permission. I've already implemented the fix (just re-naming the image files)

**Comment by RebelusQuo** [comment]
The way you contribute to the project is by issuing pull requests from a forked repository. Github should have instructions on how this works.

Simply renaming the image files would not be enough since the logic depend on the ordinal numbering to check pedestal/shahasralah/big bomb.

This is something we have been thinking of already. We are contemplating how far we want to combine this with right click functionality.
